#!/usr/bin/env python3
"""
Add host_type column to CSV files generated by vec2csv.

Adds a 'host_type' column based on the host_id field:
- 'spoofer' for hosts specified via --spoofer-hosts
- 'benign' for all other hosts

Usage:
    add_host_type.py input.csv -o output.csv [--spoofer-hosts 5,6]
    add_host_type.py input.csv --in-place [--spoofer-hosts 5]
"""

import argparse
import csv
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Add host_type column to CSV files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('input', help='Input CSV file')
    parser.add_argument('-o', '--output', help='Output CSV file')
    parser.add_argument('--in-place', action='store_true',
                        help='Modify input file in place')
    parser.add_argument('--spoofer-hosts', default='',
                        help='Comma-separated list of spoofer host indices')

    args = parser.parse_args()

    if not args.output and not args.in_place:
        parser.error("Either --output or --in-place must be specified")

    if args.output and args.in_place:
        parser.error("Cannot specify both --output and --in-place")

    # Parse spoofer hosts
    spoofer_hosts = set()
    if args.spoofer_hosts:
        for h in args.spoofer_hosts.split(','):
            h = h.strip()
            if h:
                spoofer_hosts.add(int(h))

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    # Read input CSV
    with open(input_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        if not fieldnames:
            print(f"Error: Empty or invalid CSV file: {input_path}", file=sys.stderr)
            sys.exit(1)

        # Check if host_type already exists
        if 'host_type' in fieldnames:
            print(f"Warning: host_type column already exists in {input_path}")
            # Still process to allow updating
            new_fieldnames = fieldnames
        else:
            # Insert host_type after host_id
            new_fieldnames = []
            for fn in fieldnames:
                new_fieldnames.append(fn)
                if fn == 'host_id':
                    new_fieldnames.append('host_type')

        rows = list(reader)

    # Determine output path
    if args.in_place:
        output_path = input_path
    else:
        output_path = Path(args.output)

    # Write output CSV with host_type column
    with open(output_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=new_fieldnames)
        writer.writeheader()

        for row in rows:
            host_id = int(row['host_id'])
            if host_id in spoofer_hosts:
                row['host_type'] = 'spoofer'
            else:
                row['host_type'] = 'benign'
            writer.writerow(row)

    num_spoofer = sum(1 for r in rows if int(r['host_id']) in spoofer_hosts)
    num_benign = len(rows) - num_spoofer
    print(f"Added host_type column: {num_benign} benign, {num_spoofer} spoofer events")


if __name__ == '__main__':
    main()
