#!/usr/bin/env python3
"""
Add host_type and is_spoofed columns to CSV files generated by vec2csv.

Adds columns based on the host_id and event_type fields:
- 'host_type': 'spoofer' for hosts specified via --spoofer-hosts, 'benign' otherwise
- 'is_spoofed': 1 if the row is a spoofed transmission (TX from spoofer, or RX with
                serial_number matching a spoofer), 0 otherwise

Usage:
    add_host_type.py input.csv -o output.csv [--spoofer-hosts 5,6]
    add_host_type.py input.csv --in-place [--spoofer-hosts 5]
"""

import argparse
import csv
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(
        description="Add host_type column to CSV files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument('input', help='Input CSV file')
    parser.add_argument('-o', '--output', help='Output CSV file')
    parser.add_argument('--in-place', action='store_true',
                        help='Modify input file in place')
    parser.add_argument('--spoofer-hosts', default='',
                        help='Comma-separated list of spoofer host indices')

    args = parser.parse_args()

    if not args.output and not args.in_place:
        parser.error("Either --output or --in-place must be specified")

    if args.output and args.in_place:
        parser.error("Cannot specify both --output and --in-place")

    # Parse spoofer hosts
    spoofer_hosts = set()
    if args.spoofer_hosts:
        for h in args.spoofer_hosts.split(','):
            h = h.strip()
            if h:
                spoofer_hosts.add(int(h))

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    # Read input CSV
    with open(input_path, 'r', newline='') as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        if not fieldnames:
            print(f"Error: Empty or invalid CSV file: {input_path}", file=sys.stderr)
            sys.exit(1)

        # Build new fieldnames with host_type and is_spoofed
        new_fieldnames = []
        for fn in fieldnames:
            new_fieldnames.append(fn)
            if fn == 'host_id':
                if 'host_type' not in fieldnames:
                    new_fieldnames.append('host_type')
                if 'is_spoofed' not in fieldnames:
                    new_fieldnames.append('is_spoofed')

        if 'host_type' in fieldnames:
            print(f"Warning: host_type column already exists in {input_path}")
        if 'is_spoofed' in fieldnames:
            print(f"Warning: is_spoofed column already exists in {input_path}")

        rows = list(reader)

    # Determine output path
    if args.in_place:
        output_path = input_path
    else:
        output_path = Path(args.output)

    # Write output CSV with host_type and is_spoofed columns
    with open(output_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=new_fieldnames)
        writer.writeheader()

        num_spoofed = 0
        for row in rows:
            host_id = int(row['host_id'])
            event_type = row.get('event_type', '')
            serial_number = row.get('serial_number', '')

            # Set host_type based on host_id
            if host_id in spoofer_hosts:
                row['host_type'] = 'spoofer'
            else:
                row['host_type'] = 'benign'

            # Set is_spoofed:
            # - TX event from a spoofer host
            # - RX event where serial_number matches a spoofer host
            is_spoofed = 0
            if event_type == 'TX' and host_id in spoofer_hosts:
                is_spoofed = 1
            elif event_type == 'RX' and serial_number:
                try:
                    if int(serial_number) in spoofer_hosts:
                        is_spoofed = 1
                except ValueError:
                    pass  # serial_number not an integer
            row['is_spoofed'] = is_spoofed
            if is_spoofed:
                num_spoofed += 1

            writer.writerow(row)

    num_spoofer_hosts = sum(1 for r in rows if int(r['host_id']) in spoofer_hosts)
    num_benign_hosts = len(rows) - num_spoofer_hosts
    print(f"Added columns: {num_benign_hosts} benign/{num_spoofer_hosts} spoofer host events, {num_spoofed} spoofed rows")


if __name__ == '__main__':
    main()
